//Генерация исключений с++ пример. throw c++ пример. Изучение С++ для начинающих. Урок #121 - Видео № 140. 

#include<iostream>
#include<ctime>
#include<string>
#include<fstream>
using namespace std;


//-------------------------------------------------------------------------------------------
void Foo(int value)
{
	if (value < 0)
	{
		throw exception("Число меньше 0");
	}
	
	cout << "Переманная = " << value << endl;
}
//-------------------------------------------------------------------------------------------
int main()
{
	setlocale(LC_ALL,"ru");

	try
	{
		Foo(-55);
	}
	catch (const exception &ex)
	{
		cout << "Мы поймали " << ex.what() << endl;
	}
	
	return 0;
}
//-------------------------------------------------------------------------------------------